<a href="https://colab.research.google.com/github/Giankarl0/Data-Science/blob/integration/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


 **Clase 1**



**Función para verificar si un número es primo.
 Un número primo es mayor que 1 y divisible solo por 1 y por sí mismo.**
    
    

In [ ]:
def es_primo(numero):

    if numero <= 1:
        return False
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            return False
    return True

numero = int(input("Introduce un número para verificar si es primo: "))
if es_primo(numero):
    print(f"{numero} es un número primo.")
else:
    print(f"{numero} no es un número primo.")


Introduce un número para verificar si es primo: 5
5 es un número primo.


Función para pedir tres notas al usuario, calcular el promedio y determinar si aprobó o reprobó.


In [ ]:
def calcular_promedio():

    print("Por favor, introduce tres notas (entre 0 y 5):")

    nota1 = float(input("Introduce la primera nota: "))
    nota2 = float(input("Introduce la segunda nota: "))
    nota3 = float(input("Introduce la tercera nota: "))

    promedio = (nota1 + nota2 + nota3) / 3

    if promedio >= 3.5:
        estado = "Aprobaste la materia. 🎉"
    else:
        estado = "Reprobaste la materia. 😔"

    print(f"\nEl promedio de las notas {nota1}, {nota2} y {nota3} es: {promedio:.2f}")
    print(estado)

calcular_promedio()

Por favor, introduce tres notas (entre 0 y 5):
Introduce la primera nota: 4
Introduce la segunda nota: 5
Introduce la tercera nota: 2

El promedio de las notas 4.0, 5.0 y 2.0 es: 3.67
Aprobaste la materia. 🎉


In [ ]:
def determinar_estado(promedio):

    opciones = {
        "aprobado": "Aprobaste la materia. 🎉",
        "reprobado": "Reprobaste la materia. 😔"
    }
    return opciones["aprobado"] if promedio >= 3.5 else opciones["reprobado"]

print("Bienvenido. Vamos a calcular tu promedio de notas.")
notas = []
contador = 1

while contador <= 3:
    try:
        nota = float(input(f"Introduce la nota {contador} (entre 0 y 5): "))
        if 0 <= nota <= 5:
            notas.append(nota)
            contador += 1
        else:
            print("Por favor, introduce una nota válida entre 0 y 5.")
    except ValueError:
        print("Entrada inválida. Introduce un número.")

suma = 0
for nota in notas:
    suma += nota

promedio = suma / len(notas)

estado = determinar_estado(promedio)

print(f"\nTus notas son: {notas}")
print(f"El promedio es: {promedio:.2f}")
print(estado)


Bienvenido. Vamos a calcular tu promedio de notas.
Introduce la nota 1 (entre 0 y 5): 4
Introduce la nota 2 (entre 0 y 5): 4
Introduce la nota 3 (entre 0 y 5): 2

Tus notas son: [4.0, 4.0, 2.0]
El promedio es: 3.33
Reprobaste la materia. 😔



***Clase 2***

Escribe un programa que clasifique a una persona en diferentes grupos según su edad y la primera letra de su nombre.

Si la persona tiene menos de 18 años y su nombre comienza con una vocal (A, E, I, O, U), pertenece al grupo 1.

Si la persona tiene 18 años o más y su nombre comienza con una consonante, pertenece al grupo 2.

Si no cumple ninguna de las condiciones anteriores, pertenece al grupo 3.

In [ ]:
def clasificar_persona(nombre, edad):

    primera_letra = nombre[0].upper()
    vocales = {'A', 'E', 'I', 'O', 'U'}

    if edad < 18 and primera_letra in vocales:
        return "Grupo 1"
    elif edad >= 18 and primera_letra not in vocales:
        return "Grupo 2"
    else:
        return "Grupo 3"

nombre = input("Ingresa tu nombre: ")
edad = int(input("Ingresa tu edad: "))

grupo = clasificar_persona(nombre, edad)
print(f"{nombre}, perteneces al {grupo}.")


Ingresa tu nombre: 3DLF
Ingresa tu edad: 23
3DLF, perteneces al Grupo 2.


Escribe un programa que determine el grupo al que pertenece una persona según su país de origen y la longitud de su nombre.

Si la persona es de Colombia y su nombre tiene menos de 5 caracteres, pertenece al grupo Colombia A.

Si es de México y su nombre tiene 5 o más caracteres, pertenece al grupo México B.

Si la persona no es de Colombia ni de México, pertenece al grupo Otros.

In [ ]:
def clasificar_persona(pais, nombre):
    pais = pais.upper()
    longitud_nombre = len(nombre)

    if pais == "colombia" and longitud_nombre < 5:
        return "Grupo Colombia A"
    elif pais == "mexico" or "mejico" and longitud_nombre >= 5:
        return "Grupo Mexico B"
    else:
        return "Grupo otros"

pais = input("Ingresa tu país de origen: ")
nombre = input("Ingresa tu nombre: ")

grupo = clasificar_persona(pais, nombre)
print(nombre + ", perteneces al " + grupo)



Ingresa tu país de origen: mejico
Ingresa tu nombre: sdfsdfsdfsdf
sdfsdfsdfsdf, perteneces al Grupo México B


Una empresa otorga una calificación a los proyectos desarrollados por sus empleados en función de la puntuación obtenida al final del año.

Las puntuaciones posibles son: 1.0, 1.5, 2.0 o más. Según la puntuación, se asigna un nivel (bajo, medio, alto, excelente) y un bono.

La empresa paga una cantidad de dinero proporcional a la puntuación obtenida, multiplicada por 3 millones.

Por ejemplo:

Si la puntuación es 1.0, el bono será de 3 millones.

Si la puntuación es 1.5, el bono será de 4. millones 500.

Si la puntuación es 2.0, el bono será de 6 millones.

Si la puntuación es 2.5, el bono será de 7 millones 500.


Escribe un programa que lea la puntuación de un proyecto y determine el nivel de rendimiento y el bono que recibirá el empleado.

In [ ]:
def calcular_bono(puntuacion):
    if puntuacion < 1.0:
        nivel = "No elegible"
        bono = 0
    elif puntuacion == 1.0:
        nivel = "Bajo"
        bono = 1.0 * 3_000_000
    elif puntuacion == 1.5:
        nivel = "Medio"
        bono = 1.5 * 3_000_000
    elif puntuacion == 2.0:
        nivel = "Alto"
        bono = 2.0 * 3_000_000
    elif puntuacion >= 2.5:
        nivel = "Excelente"
        bono = puntuacion * 3_000_000
    else:
        nivel = "No válido"
        bono = 0

    return nivel, bono

try:
    puntuacion = float(input("Ingresa la puntuación del proyecto (1.0, 1.5, 2.0 o más): "))
    nivel, bono = calcular_bono(puntuacion)
    if nivel == "No válido" or puntuacion < 1.0:
        print("La puntuación ingresada no es válida.")
    else:
        print(f"Nivel de rendimiento: {nivel}")
        print(f"Bono a recibir: ${bono}")
except ValueError:
    print("Por favor, ingresa un valor numérico válido.")



Ingresa la puntuación del proyecto (1.0, 1.5, 2.0 o más): 3
Nivel de rendimiento: Excelente
Bono a recibir: $9000000.0


Sistema de Gestión de Productos.

Tiendas ARA demando a la empresa prestadora de servicio TI por un mal desarrollo en un software que le ocasionaron pérdidas millonarias. Mientras esta situación se resuelve el negocio debe continuar y por esta razón lo contratan a usted como Ingeniero(a) de Sistemas para que trabaje en una nueva iniciativa: Sistema de Gestión de Productos (SIGEP).

Tras múltiples reuniones se concluyó que SIGEP debe contar con un menú que permita al usuario Agregar un nuevo producto.

Eliminar un producto.

Actualizar la cantidad y precio de un producto.

Mostrar el inventario de productos que están por agotarse, es decir, cuyas cantidades sean inferiores a 5.

In [ ]:
class Producto:
    def __init__(self, id_producto, nombre, cantidad, precio):
        self.id_producto = id_producto
        self.nombre = nombre
        self.cantidad = cantidad
        self.precio = precio

    def actualizar_precio_y_cantidad(self, cantidad, precio):
        self.cantidad = cantidad
        self.precio = precio

    def __str__(self):
        return f"ID: {self.id_producto}, Nombre: {self.nombre}, Cantidad: {self.cantidad}, Precio: {self.precio}"

class SistemaGestionProductos:
    def __init__(self):
        self.productos = {}

    def agregar_producto(self):
        id_producto = input("Ingrese el ID del producto: ")
        nombre = input("Ingrese el nombre del producto: ")
        cantidad = int(input("Ingrese la cantidad del producto: "))
        precio = float(input("Ingrese el precio del producto: "))
        if id_producto in self.productos:
            print("El producto ya existe.")
        else:
            self.productos[id_producto] = Producto(id_producto, nombre, cantidad, precio)
            print(f"Producto {nombre} agregado correctamente.")

    def eliminar_producto(self):
        id_producto = input("Ingrese el ID del producto a eliminar: ")
        if id_producto in self.productos:
            del self.productos[id_producto]
            print(f"Producto con ID {id_producto} eliminado.")
        else:
            print("Producto no encontrado.")

    def actualizar_producto(self):
        id_producto = input("Ingrese el ID del producto a actualizar: ")
        if id_producto in self.productos:
            cantidad = int(input("Ingrese la nueva cantidad: "))
            precio = float(input("Ingrese el nuevo precio: "))
            self.productos[id_producto].actualizar_precio_y_cantidad(cantidad, precio)
            print("Producto actualizado correctamente.")
        else:
            print("Producto no encontrado.")

    def mostrar_productos_por_agotarse(self):
        productos_agotados = [p for p in self.productos.values() if p.cantidad < 5]
        if productos_agotados:
            print("Productos por agotarse:")
            for producto in productos_agotados:
                print(producto)
        else:
            print("No hay productos por agotarse.")

    def mostrar_menu(self):
        while True:
            print("\n--- Sistema de Gestión de Productos (SIGEP) ---")
            print("1. Agregar un nuevo producto")
            print("2. Eliminar un producto")
            print("3. Actualizar cantidad y precio de un producto")
            print("4. Mostrar productos por agotarse")
            print("5. Salir")
            opcion = input("Seleccione una opción: ")

            if opcion == '1':
                self.agregar_producto()
            elif opcion == '2':
                self.eliminar_producto()
            elif opcion == '3':
                self.actualizar_producto()
            elif opcion == '4':
                self.mostrar_productos_por_agotarse()
            elif opcion == '5':
                print("Saliendo del sistema...")
                break
            else:
                print("Opción no válida, por favor intente de nuevo.")

if __name__ == "__main__":
    sistema = SistemaGestionProductos()
    sistema.mostrar_menu()



--- Sistema de Gestión de Productos (SIGEP) ---
1. Agregar un nuevo producto
2. Eliminar un producto
3. Actualizar cantidad y precio de un producto
4. Mostrar productos por agotarse
5. Salir
Seleccione una opción: 1
Ingrese el ID del producto: 1
Ingrese el nombre del producto: soap
Ingrese la cantidad del producto: 12
Ingrese el precio del producto: 2000
Producto soap agregado correctamente.

--- Sistema de Gestión de Productos (SIGEP) ---
1. Agregar un nuevo producto
2. Eliminar un producto
3. Actualizar cantidad y precio de un producto
4. Mostrar productos por agotarse
5. Salir
Seleccione una opción: 4
No hay productos por agotarse.

--- Sistema de Gestión de Productos (SIGEP) ---
1. Agregar un nuevo producto
2. Eliminar un producto
3. Actualizar cantidad y precio de un producto
4. Mostrar productos por agotarse
5. Salir
Seleccione una opción: 5
Saliendo del sistema...


**Clase 3**

NumPy es una biblioteca de código abierto para Python que se utiliza para realizar cálculos numéricos y estadísticas, especialmente en la ciencia de datos y la inteligencia artificial:

Permite crear y manipular vectores y matrices multidimensionales
Ofrece una gran colección de funciones matemáticas de alto nivel
Es fundamental para el análisis de datos, el aprendizaje automático y la computación científica

Algunas de las características de NumPy son:
Se integra fácilmente con C/C++ y Fortran
Permite trabajar con una variedad de tipos POD (Plain Old Data)
Invoca métodos de forma vectorizada

Permite realizar operaciones aritméticas con arreglos
Es interoperable y soporta una amplia gama de hardware y plataformas de computación

Es fácil de usar y su sintaxis de alto nivel lo hace accesible para programadores de cualquier nivel de experiencia

Algunas funciones de NumPy para crear arrays son:
array(): Crea un array a partir de otras colecciones de datos de Python, como listas o tuplas
zeros(): Inicializa un array con todos los valores a 0
ones(): Inicializa un array con todos los valores a 1
full(): Inicializa un array con todos los valores a un valor predeterminado
arange(): Emula la secuencia nativa de Python range(), pero permite usar límites y pasos con valores reales
NumPy fue lanzado en 2005 por el científico de datos Travis Oliphant.

In [ ]:
import numpy as np

numeros_naturales = np.array([0,1,2,3,4,5,6,7,8,9])

numeros_naturales

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
multiplicar_3 = numeros_naturales * 2

multiplicar_3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
numeros_naturales.max()

9

In [ ]:
numeros_naturales.sum()

45

In [ ]:
numeros_naturales.min()

In [ ]:
numeros_naturales[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
numeros_naturales[:2]

array([0, 1])

In [ ]:
numeros_naturales[3]

3

Array multidimencional


In [ ]:
array_multidimencional = np.array([[1,2,3,4],[5,6,7,8]])
array_multidimencional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
array_multidimencional_3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array_multidimencional_3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Mostrar fila

In [ ]:
array_multidimencional_3[0]

array([1, 2, 3, 4])

Mostrar fila y columna

In [ ]:
array_multidimencional_3[0][1]

2

Como ver los valores desde la fila 0 hasta la 2

In [ ]:
array_multidimencional_3[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
array_multidimencional_3[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
array_multidimencional_3.max()

12

In [ ]:
array_multidimencional_3.max(axis=0)

array([ 9, 10, 11, 12])

In [ ]:
array_multidimencional_3.max(axis=1)

array([ 4,  8, 12])

¿Qué es pandas?

 En Computación y Ciencia de datos, pandas es una biblioteca de software escrita como extensión de Numpy para manipulación y análisis de datos para el lenguaje de programación Python. En particular, ofrece estructuras de datos y operaciones para manipular tablas numéricas y series temporales.

In [ ]:
import pandas as pd

futbol_dic = {
    "player": ["leonel messi", "cristiano ronaldo"],
    "year": [2016,2016],
    "goals": [37,25],
}

data = pd.DataFrame(futbol_dic)
data

player  year  goals
0       leonel messi  2016     37
1  cristiano ronaldo  2016     25

Vamos a tratar de datos de un archivo externo de Drive


In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

import numpy as np
import pandas as pd

import plotly.express as px

path_file="/content/sample_data/california_housing_test.csv"
df=pd.read_csv(path_file, sep=",",header=0)
print(df.head())
print(df.shape)

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
(3000, 9)


Funciones de Pandas

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
df['housing_median_age'].value_counts()

housing_median_age
52.0    173
35.0    118
36.0    115
16.0    107
34.0    102
17.0    100
32.0     91
37.0     88
26.0     88
25.0     86
33.0     85
15.0     77
19.0     76
18.0     76
30.0     76
24.0     75
29.0     75
27.0     74
38.0     64
20.0     63
21.0     61
22.0     60
28.0     58
14.0     57
31.0     57
41.0     56
43.0     56
39.0     55
23.0     53
44.0     51
45.0     51
42.0     51
40.0     43
46.0     41
11.0     41
12.0     41
13.0     41
5.0      39
48.0     34
10.0     30
4.0      28
9.0      27
6.0      25
8.0      25
47.0     22
49.0     21
7.0      20
50.0     16
3.0      12
51.0     11
2.0       6
1.0       2
Name: count, dtype: int64

In [ ]:
df.sort_values('housing_median_age')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
842     -117.95     35.08                 1.0         83.0            15.0   
1115    -116.95     33.86                 1.0          6.0             2.0   
2117    -117.51     34.16                 2.0        718.0            98.0   
2429    -117.20     33.58                 2.0      30450.0          5033.0   
495     -122.29     37.82                 2.0        158.0            43.0   
...         ...       ...                 ...          ...             ...   
717     -122.27     37.86                52.0       2307.0           583.0   
708     -118.21     33.97                52.0       4220.0           908.0   
1826    -122.04     37.00                52.0       3365.0           644.0   
754     -121.49     38.56                52.0       1777.0           368.0   
1499    -122.21     37.79                52.0        762.0           190.0   

      population  households  median_income  median_house_value  
842         32.0        15.0         4.8750            141700.0  
1115         8.0         2.0         1.6250             55000.0  
2117       119.0        50.0         4.1000            315000.0  
2429      9419.0      3197.0         4.5936            174300.0  
495         94.0        57.0         2.5625             60000.0  
...          ...         ...            ...                 ...  
717       1127.0       548.0         1.8447            198200.0  
708       3731.0       892.0         3.1901            167600.0  
1826       796.0       333.0         2.9712            116600.0  
754        624.0       350.0         3.6729            137800.0  
1499       600.0       195.0         3.0893            125000.0  

[3000 rows x 9 columns]